CREATE TABLE IF NOT EXISTS RESTAURANT (
    RESTAURANT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(25) NOT NULL,
    LOCATION VARCHAR(25)
);

CREATE TABLE IF NOT EXISTS RESTAURANT_TABLE (
    TABLE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CAPACITY BIGINT NOT NULL,
    RESTAURANT_ID BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS CUSTOMER (
    CUSTOMER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(25) NOT NULL,
    PHONE_NUMBER VARCHAR(25) NOT NULL
);

CREATE TABLE IF NOT EXISTS RESERVATION (
    RESERVATION_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    RESTAURANT_ID BIGINT NOT NULL,
    CUSTOMER_ID BIGINT NOT NULL,
    RESTAURANT_TABLE_ID BIGINT NOT NULL,
    RES_DATE DATE,
    PARTY_SIZE BIGINT
);

ALTER TABLE RESTAURANT_TABLE ADD FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANT(RESTAURANT_ID);
ALTER TABLE RESERVATION ADD FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANT(RESTAURANT_ID);
ALTER TABLE RESERVATION ADD FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID);
ALTER TABLE RESERVATION ADD FOREIGN KEY (RESTAURANT_TABLE_ID) REFERENCES RESTAURANT_TABLE(TABLE_ID);

CREATE INDEX IDX_RES_DATE_ ON RESERVATION(RES_DATE);